
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ig_user?useSSL=false
    username: root
    password: nirav

    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true

server:
    port: 9000


